// Code generated by protoc-gen-go-cosmos-orm. DO NOT EDIT.

package authnv1

import (
	context "context"
	ormlist "github.com/cosmos/cosmos-sdk/orm/model/ormlist"
	ormtable "github.com/cosmos/cosmos-sdk/orm/model/ormtable"
	ormerrors "github.com/cosmos/cosmos-sdk/orm/types/ormerrors"
)

type AccountTable interface {
	Insert(ctx context.Context, account *Account) error
	InsertReturningId(ctx context.Context, account *Account) (uint64, error)
	Update(ctx context.Context, account *Account) error
	Save(ctx context.Context, account *Account) error
	Delete(ctx context.Context, account *Account) error
	Has(ctx context.Context, id uint64) (found bool, err error)
	// Get returns nil and an error which responds true to ormerrors.IsNotFound() if the record was not found.
	Get(ctx context.Context, id uint64) (*Account, error)
	HasByAddress(ctx context.Context, address []byte) (found bool, err error)
	// GetByAddress returns nil and an error which responds true to ormerrors.IsNotFound() if the record was not found.
	GetByAddress(ctx context.Context, address []byte) (*Account, error)
	List(ctx context.Context, prefixKey AccountIndexKey, opts ...ormlist.Option) (AccountIterator, error)
	ListRange(ctx context.Context, from, to AccountIndexKey, opts ...ormlist.Option) (AccountIterator, error)
	DeleteBy(ctx context.Context, prefixKey AccountIndexKey) error
	DeleteRange(ctx context.Context, from, to AccountIndexKey) error

	doNotImplement()
}

type AccountIterator struct {
	ormtable.Iterator
}

func (i AccountIterator) Value() (*Account, error) {
	var account Account
	err := i.UnmarshalMessage(&account)
	return &account, err
}

type AccountIndexKey interface {
	id() uint32
	values() []interface{}
	accountIndexKey()
}

// primary key starting index..
type AccountPrimaryKey = AccountIdIndexKey

type AccountIdIndexKey struct {
	vs []interface{}
}

func (x AccountIdIndexKey) id() uint32            { return 0 }
func (x AccountIdIndexKey) values() []interface{} { return x.vs }
func (x AccountIdIndexKey) accountIndexKey()      {}

func (this AccountIdIndexKey) WithId(id uint64) AccountIdIndexKey {
	this.vs = []interface{}{id}
	return this
}

type AccountAddressIndexKey struct {
	vs []interface{}
}

func (x AccountAddressIndexKey) id() uint32            { return 1 }
func (x AccountAddressIndexKey) values() []interface{} { return x.vs }
func (x AccountAddressIndexKey) accountIndexKey()      {}

func (this AccountAddressIndexKey) WithAddress(address []byte) AccountAddressIndexKey {
	this.vs = []interface{}{address}
	return this
}

type accountTable struct {
	table ormtable.AutoIncrementTable
}

func (this accountTable) Insert(ctx context.Context, account *Account) error {
	return this.table.Insert(ctx, account)
}

func (this accountTable) Update(ctx context.Context, account *Account) error {
	return this.table.Update(ctx, account)
}

func (this accountTable) Save(ctx context.Context, account *Account) error {
	return this.table.Save(ctx, account)
}

func (this accountTable) Delete(ctx context.Context, account *Account) error {
	return this.table.Delete(ctx, account)
}

func (this accountTable) InsertReturningId(ctx context.Context, account *Account) (uint64, error) {
	return this.table.InsertReturningPKey(ctx, account)
}

func (this accountTable) Has(ctx context.Context, id uint64) (found bool, err error) {
	return this.table.PrimaryKey().Has(ctx, id)
}

func (this accountTable) Get(ctx context.Context, id uint64) (*Account, error) {
	var account Account
	found, err := this.table.PrimaryKey().Get(ctx, &account, id)
	if err != nil {
		return nil, err
	}
	if !found {
		return nil, ormerrors.NotFound
	}
	return &account, nil
}

func (this accountTable) HasByAddress(ctx context.Context, address []byte) (found bool, err error) {
	return this.table.GetIndexByID(1).(ormtable.UniqueIndex).Has(ctx,
		address,
	)
}

func (this accountTable) GetByAddress(ctx context.Context, address []byte) (*Account, error) {
	var account Account
	found, err := this.table.GetIndexByID(1).(ormtable.UniqueIndex).Get(ctx, &account,
		address,
	)
	if err != nil {
		return nil, err
	}
	if !found {
		return nil, ormerrors.NotFound
	}
	return &account, nil
}

func (this accountTable) List(ctx context.Context, prefixKey AccountIndexKey, opts ...ormlist.Option) (AccountIterator, error) {
	it, err := this.table.GetIndexByID(prefixKey.id()).List(ctx, prefixKey.values(), opts...)
	return AccountIterator{it}, err
}

func (this accountTable) ListRange(ctx context.Context, from, to AccountIndexKey, opts ...ormlist.Option) (AccountIterator, error) {
	it, err := this.table.GetIndexByID(from.id()).ListRange(ctx, from.values(), to.values(), opts...)
	return AccountIterator{it}, err
}

func (this accountTable) DeleteBy(ctx context.Context, prefixKey AccountIndexKey) error {
	return this.table.GetIndexByID(prefixKey.id()).DeleteBy(ctx, prefixKey.values()...)
}

func (this accountTable) DeleteRange(ctx context.Context, from, to AccountIndexKey) error {
	return this.table.GetIndexByID(from.id()).DeleteRange(ctx, from.values(), to.values())
}

func (this accountTable) doNotImplement() {}

var _ AccountTable = accountTable{}

func NewAccountTable(db ormtable.Schema) (AccountTable, error) {
	table := db.GetTable(&Account{})
	if table == nil {
		return nil, ormerrors.TableNotFound.Wrap(string((&Account{}).ProtoReflect().Descriptor().FullName()))
	}
	return accountTable{table.(ormtable.AutoIncrementTable)}, nil
}

type AccountSequenceTable interface {
	Insert(ctx context.Context, accountSequence *AccountSequence) error
	Update(ctx context.Context, accountSequence *AccountSequence) error
	Save(ctx context.Context, accountSequence *AccountSequence) error
	Delete(ctx context.Context, accountSequence *AccountSequence) error
	Has(ctx context.Context, id uint64) (found bool, err error)
	// Get returns nil and an error which responds true to ormerrors.IsNotFound() if the record was not found.
	Get(ctx context.Context, id uint64) (*AccountSequence, error)
	List(ctx context.Context, prefixKey AccountSequenceIndexKey, opts ...ormlist.Option) (AccountSequenceIterator, error)
	ListRange(ctx context.Context, from, to AccountSequenceIndexKey, opts ...ormlist.Option) (AccountSequenceIterator, error)
	DeleteBy(ctx context.Context, prefixKey AccountSequenceIndexKey) error
	DeleteRange(ctx context.Context, from, to AccountSequenceIndexKey) error

	doNotImplement()
}

type AccountSequenceIterator struct {
	ormtable.Iterator
}

func (i AccountSequenceIterator) Value() (*AccountSequence, error) {
	var accountSequence AccountSequence
	err := i.UnmarshalMessage(&accountSequence)
	return &accountSequence, err
}

type AccountSequenceIndexKey interface {
	id() uint32
	values() []interface{}
	accountSequenceIndexKey()
}

// primary key starting index..
type AccountSequencePrimaryKey = AccountSequenceIdIndexKey

type AccountSequenceIdIndexKey struct {
	vs []interface{}
}

func (x AccountSequenceIdIndexKey) id() uint32               { return 0 }
func (x AccountSequenceIdIndexKey) values() []interface{}    { return x.vs }
func (x AccountSequenceIdIndexKey) accountSequenceIndexKey() {}

func (this AccountSequenceIdIndexKey) WithId(id uint64) AccountSequenceIdIndexKey {
	this.vs = []interface{}{id}
	return this
}

type accountSequenceTable struct {
	table ormtable.Table
}

func (this accountSequenceTable) Insert(ctx context.Context, accountSequence *AccountSequence) error {
	return this.table.Insert(ctx, accountSequence)
}

func (this accountSequenceTable) Update(ctx context.Context, accountSequence *AccountSequence) error {
	return this.table.Update(ctx, accountSequence)
}

func (this accountSequenceTable) Save(ctx context.Context, accountSequence *AccountSequence) error {
	return this.table.Save(ctx, accountSequence)
}

func (this accountSequenceTable) Delete(ctx context.Context, accountSequence *AccountSequence) error {
	return this.table.Delete(ctx, accountSequence)
}

func (this accountSequenceTable) Has(ctx context.Context, id uint64) (found bool, err error) {
	return this.table.PrimaryKey().Has(ctx, id)
}

func (this accountSequenceTable) Get(ctx context.Context, id uint64) (*AccountSequence, error) {
	var accountSequence AccountSequence
	found, err := this.table.PrimaryKey().Get(ctx, &accountSequence, id)
	if err != nil {
		return nil, err
	}
	if !found {
		return nil, ormerrors.NotFound
	}
	return &accountSequence, nil
}

func (this accountSequenceTable) List(ctx context.Context, prefixKey AccountSequenceIndexKey, opts ...ormlist.Option) (AccountSequenceIterator, error) {
	it, err := this.table.GetIndexByID(prefixKey.id()).List(ctx, prefixKey.values(), opts...)
	return AccountSequenceIterator{it}, err
}

func (this accountSequenceTable) ListRange(ctx context.Context, from, to AccountSequenceIndexKey, opts ...ormlist.Option) (AccountSequenceIterator, error) {
	it, err := this.table.GetIndexByID(from.id()).ListRange(ctx, from.values(), to.values(), opts...)
	return AccountSequenceIterator{it}, err
}

func (this accountSequenceTable) DeleteBy(ctx context.Context, prefixKey AccountSequenceIndexKey) error {
	return this.table.GetIndexByID(prefixKey.id()).DeleteBy(ctx, prefixKey.values()...)
}

func (this accountSequenceTable) DeleteRange(ctx context.Context, from, to AccountSequenceIndexKey) error {
	return this.table.GetIndexByID(from.id()).DeleteRange(ctx, from.values(), to.values())
}

func (this accountSequenceTable) doNotImplement() {}

var _ AccountSequenceTable = accountSequenceTable{}

func NewAccountSequenceTable(db ormtable.Schema) (AccountSequenceTable, error) {
	table := db.GetTable(&AccountSequence{})
	if table == nil {
		return nil, ormerrors.TableNotFound.Wrap(string((&AccountSequence{}).ProtoReflect().Descriptor().FullName()))
	}
	return accountSequenceTable{table}, nil
}

type StateStore interface {
	AccountTable() AccountTable
	AccountSequenceTable() AccountSequenceTable

	doNotImplement()
}

type stateStore struct {
	account         AccountTable
	accountSequence AccountSequenceTable
}

func (x stateStore) AccountTable() AccountTable {
	return x.account
}

func (x stateStore) AccountSequenceTable() AccountSequenceTable {
	return x.accountSequence
}

func (stateStore) doNotImplement() {}

var _ StateStore = stateStore{}

func NewStateStore(db ormtable.Schema) (StateStore, error) {
	accountTable, err := NewAccountTable(db)
	if err != nil {
		return nil, err
	}

	accountSequenceTable, err := NewAccountSequenceTable(db)
	if err != nil {
		return nil, err
	}

	return stateStore{
		accountTable,
		accountSequenceTable,
	}, nil
}
